from __future__ import annotations

"""Pydantic models for API requests and responses."""

from typing import Literal

from pydantic import BaseModel, Field


class TranscriptionSegment(BaseModel):
    """Single recognized speech segment with optional language tag."""

    start_ms: int = Field(ge=0)
    end_ms: int = Field(ge=0)
    text: str
    language: str | None = None


class SttMetadata(BaseModel):
    """Technical metadata describing source and normalized audio."""

    provider: str = "azure_speech"
    source_sample_rate_hz: int = Field(ge=1)
    source_channels: int = Field(ge=1)
    source_sample_width_bytes: int = Field(ge=1)
    normalized_sample_rate_hz: int = Field(default=16000, ge=1)
    normalized_channels: int = Field(default=1, ge=1)
    normalized_sample_width_bytes: int = Field(default=2, ge=1)
    duration_sec: float = Field(ge=0)


class TranscriptionResult(BaseModel):
    """Transcription payload returned by STT stage."""

    text: str
    segments: list[TranscriptionSegment] | None = None
    detected_languages: list[str] | None = None
    stt_metadata: SttMetadata


class ClassificationExtras(BaseModel):
    """Optional extra analytical fields generated by classifier."""

    intent: str | None = None
    sentiment: str | None = None
    compliance_flags: list[str] = Field(default_factory=list)
    escalation: bool | None = None
    summary: str | None = None
    evidence: list[str] = Field(default_factory=list)
    key_entities: list[str] = Field(default_factory=list)


class ClassificationResult(BaseModel):
    """Primary classification output for caller and category."""

    caller_type: Literal["NATURAL", "JURIDICAL", "UNKNOWN"]
    caller_type_confidence: float = Field(ge=0, le=1)
    call_category: str
    call_category_confidence: float = Field(ge=0, le=1)
    extras: ClassificationExtras | None = None
    model: str
    prompt_version: str


class TimingsMs(BaseModel):
    """Per-stage processing duration metrics in milliseconds."""

    normalize: int = Field(ge=0)
    stt: int = Field(ge=0)
    clf: int = Field(ge=0)
    total: int = Field(ge=0)


class ProcessCallResponse(BaseModel):
    """Top-level successful response model for `/v1/calls/process`."""

    call_id: str
    transcription: TranscriptionResult
    classification: ClassificationResult
    timings_ms: TimingsMs


class ErrorResponse(BaseModel):
    """Top-level error response model used by all API failures."""

    error_code: str
    message: str
    call_id: str | None = None
